steps:
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        cd ./01-sample-instance
        terraform init

- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd ./01-sample-instance
      terraform plan